spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/sichange
    username: sichange
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone=UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect